export const flyers = {
  title: "Flyer Design",
  images: [
    "../assets/images/portfolio/flyer/Akka ICT 1 Preview.jpg",
    "../assets/images/portfolio/flyer/awrudu 1.jpg",
    "../assets/images/portfolio/flyer/awrudu 2.jpg",
    "../assets/images/portfolio/flyer/Christmas.jpg",
    "../assets/images/portfolio/flyer/dr chem Post Preview.jpg",
    "../assets/images/portfolio/flyer/dr chem Post Preview.jpg",
    "../assets/images/portfolio/flyer/DS Post Preview.jpg",
    "../assets/images/portfolio/flyer/fos 1.jpg",
    "../assets/images/portfolio/flyer/Fos 2.jpg",
    "../assets/images/portfolio/flyer/fos 3.jpg",
    "../assets/images/portfolio/flyer/hikari  seminar Post Preview.jpg",
    "../assets/images/portfolio/flyer/hikari julu intake.jpg",
    "../assets/images/portfolio/flyer/independence.jpg",
    "../assets/images/portfolio/flyer/mrp6 Post 1 Preview.jpg",
    "../assets/images/portfolio/flyer/mrp6 Post 3Preview.jpg",
    "../assets/images/portfolio/flyer/mrp6 status 2 Preview.jpg",
    "../assets/images/portfolio/flyer/Resturant.jpg",
    "../assets/images/portfolio/flyer/Tshaka Chem post preview.jpg",
    "../assets/images/portfolio/flyer/පරමාණුක ව්‍යුහය Post Preview.jpg",
  ],
};
