export const flyers = {
  title: "Flyer Design",
  images: [
    "assets/images/portfolio/flyer/Akura.jpg",
    "assets/images/portfolio/flyer/brand eka Post Preview.jpg",
    "assets/images/portfolio/flyer/Chathun Desitha Seminar .jpg",
    "assets/images/portfolio/flyer/designo Post Preview.jpg",
    "assets/images/portfolio/flyer/dr chem Post Preview.jpg",
    "assets/images/portfolio/flyer/DS Post Preview.jpg",
    "assets/images/portfolio/flyer/Dulshika Post Preview.jpg",
    "assets/images/portfolio/flyer/Guitar Class Post Preview.jpg",
    "assets/images/portfolio/flyer/hikari  seminar Post Preview.jpg",
    "assets/images/portfolio/flyer/hikari exam.jpg",
    "assets/images/portfolio/flyer/hikari julu intake.jpg",
    "assets/images/portfolio/flyer/hot water shower repair Post Preview.jpg",
    "assets/images/portfolio/flyer/mrp6 mana 2026 Post Preview.jpg",
    "assets/images/portfolio/flyer/Sparkware Post Preview.jpg",
    "assets/images/portfolio/flyer/we design what you want preview dark.jpg",
    "assets/images/portfolio/flyer/පරමාණුක ව්‍යුහය Post Preview.jpg",
  ],
};
